apiVersion: v1
kind: Template
metadata:
  name: goblogo-template
  annotations:
    description: "blog written in golang"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "${NAME}"
    stringData:
      webhook-secret: "${GITHUB_WEBHOOK_SECRET}"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}-base
      annotations:
        description: "The base image."
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
      annotations:
        description: "The built application image."
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: goblogo
      annotations:
        description: Defines how to build the application
    spec:
      triggers:
        - type: "ImageChange"
        - type: "ConfigChange"
        - type: "GitHub"
          github:
            secret: webhook-secret
      source:
        git:
          uri: "https://github.com/austin880625/test_go"
          ref: "master"
      strategy:
        sourceStrategy:
          from:
            kind: "ImageStreamTag"
            name: "${NAME}-base:latest"
      output:
        to:
          kind: "ImageStreamTag"
          name: "${NAME}:latest"

labels:
  template: "goblogo-template"
  app: "goblogo"

parameters:
  - name: NAME
    description: "The name assigned to all of the frontend objects defined in this template."
    value: "goblogo"
  - name: NAMESPACE
    description: ""
    value: "goblogo"
  - name: GITHUB_WEBHOOK_SECRET
    description: "The secret contained in the webhook url."
